services:
  backend:
    build:
      context: . # Path to your backend Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expose backend on port 3000
    networks:
      - app-network

  frontend:
    build:
      context: ./client # Path to your frontend Dockerfile
      dockerfile: Dockerfile
    ports:
      - "80:80" # Expose frontend on port 80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
